Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace GeorgianBudgetSaver.Models
{
    public class Order
    {
        public int OrderId { get; set; }
        public string CustomerId { get; set; }
        [Required]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }
        [Required]
        [Display(Name ="Last Name")]
        public string LastName { get; set; }
        [Required]
        public string Address { get; set; }
        [Required]
        public string City { get; set; }
        [Required]
        public string Province { get; set; }
        [Required]
        public string PostalCode { get; set; }
        [Required]
        public string Phone { get; set; }
        public string Email { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public DateTime OrderDate { get; set; }
        [Required]
        [Column(TypeName = "decimal(18,2)")]
        public Decimal Total { get; set; }
        public ICollection<OrderDetail> OrderDetails { get; set; }
    }
}

Controllers/CartsController.cs
using GeorgianBudgetSaver.Data;
using GeorgianBudgetSaver.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Stripe;
using System.Configuration;
using Microsoft.Extensions.Configuration;
using Stripe.Checkout;

namespace GeorgianBudgetSaver.Controllers
{
    public class CartsController : Controller
    {
        private readonly ApplicationDbContext _context;
        IConfiguration _configuration;

        public CartsController(ApplicationDbContext context, IConfiguration configuration)
        {
            _context = context;
            _configuration = configuration;
        }

        [HttpPost]
        public IActionResult RemoveFromCart(int productId)
        {
            //remove from session
            List<Cart> cartList = JsonConvert.DeserializeObject<List<Cart>>(HttpContext.Session.GetString("cart"));
            cartList = cartList.Where(b => b.BookId != productId).ToList();
            string jsonString = System.Text.Json.JsonSerializer.Serialize(cartList);

            HttpContext.Session.SetString("cart", jsonString);

            return RedirectToAction("Checkout");

        }
        public async Task<IActionResult> Checkout()
        {
            if (User.IsInRole("Administrator"))
            {
                return RedirectToAction("Index", "Home");
            }
            int items = 0;
            decimal priceSum = 0;
            List<Book> books = new List<Book>();
            List<string> provinces = new List<string>();
            provinces.Add("Alberta");
            provinces.Add("British Columbia");
            provinces.Add("Manitoba");
            provinces.Add("New Brunswick");
            provinces.Add("Newfoundland and Labrador");
            provinces.Add("Northwest Territories");
            provinces.Add("Nova Scotia");
            provinces.Add("Nunavut");
            provinces.Add("Ontario");
            provinces.Add("Prince Edward Island");
            provinces.Add("Quebec");
            provinces.Add("Saskatchewan");
            provinces.Add("Yukon");
            if (HttpContext.Session.GetString("cart") != null)
            {
                List<Cart> cartList = JsonConvert.DeserializeObject<List<Cart>>(HttpContext.Session.GetString("cart"));
                if (cartList.Count() > 0)
                {
                    var applicationDbContext = await _context.Books.Include(b => b.CourseProgram).ToListAsync();
                    cartList.ForEach((obj) =>
                    {
                        items = items + obj.Quantity;
                        priceSum = priceSum + obj.Quantity * obj.Price;
                        books.Add(applicationDbContext.Find(b => b.BookId == obj.BookId));
                    });
                    ViewBag.Books = books;
                }
            }
            ViewBag.Provinces = provinces;
            ViewBag.Price = priceSum;
            ViewBag.Quantity = items;
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Customer")]
        [ValidateAntiForgeryToken]
        public IActionResult Checkout([Bind("FirstName,LastName,Address,City,Province,PostalCode,Phone,Email,OrderDate,Total")] Models.Order order)
        {

            order.OrderDate = DateTime.Now.Date;
            order.CustomerId = User.Identity.Name;
            if (HttpContext.Session.GetString("cart") == null)
            {
                return RedirectToAction("Checkout");
            }
            List<Cart> cartList = JsonConvert.DeserializeObject<List<Cart>>(HttpContext.Session.GetString("cart"));
            if (cartList.Count() <= 0)
            {
                return RedirectToAction("Checkout");
            }
            order.Total = (from cart in cartList select cart.Price * cart.Quantity).Sum();
            string jsonString = System.Text.Json.JsonSerializer.Serialize(order);
            HttpContext.Session.SetString("order", jsonString);

            return RedirectToAction("Payment");
        }
        [Authorize(Roles = "Customer")]
        public IActionResult Payment()
        {
            var orderObj = JsonConvert.DeserializeObject<Models.Order>(HttpContext.Session.GetString("order"));
            ViewData["Total"] = orderObj.Total;
            ViewData["PublishableKey"] = _configuration.GetSection("Stripe")["PublishableKey"];

            return View();
        }
        [Authorize(Roles = "Customer")]
        [HttpPost]
        public IActionResult ProcessPayment()
        {
            Models.Order orderObj = JsonConvert.DeserializeObject<Models.Order>(HttpContext.Session.GetString("order"));
            //secret key
            StripeConfiguration.ApiKey = _configuration.GetSection("Stripe")["SecretKey"];

            var options = new SessionCreateOptions
            {
                PaymentMethodTypes = new List<string>
                {
                  "card",
                },
                LineItems = new List<SessionLineItemOptions>
                {
                  new SessionLineItemOptions
                  {
                    PriceData = new SessionLineItemPriceDataOptions
                    {
                      UnitAmount = (long?)(orderObj.Total * 100),
                      Currency = "cad",
                      ProductData = new SessionLineItemPriceDataProductDataOptions
                      {
                        Name = "Georgian Budget Saver Purchase",
                      },
                    },
                    Quantity = 1,
                  },
                },
                Mode = "payment",
                SuccessUrl = "https://" + Request.Host + "/Orders/Create",
                CancelUrl = "https://" + Request.Host + "/Carts/Checkout",
            };
            var service = new SessionService();
            Session session = service.Create(options);
            return Json(new { id = session.Id });
        }
    }
}

Controllers/OrderDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GeorgianBudgetSaver.Data;
using GeorgianBudgetSaver.Models;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;

namespace GeorgianBudgetSaver.Controllers
{
    public class OrderDetailsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OrderDetailsController(ApplicationDbContext context)
        {
            _context = context;
        }
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        // GET: OrderDetails
        public IActionResult DetailsWithOrder(int orderId)
        {
            var applicationDbContext = _context.OrderDetails.Include(o => o.Book).Where(od => od.OrderId == orderId).OrderBy(o => o.Book.Title).ToList();
            applicationDbContext.ForEach(od =>
            {
                od.Book.CourseProgram = _context.CoursePrograms.Find(od.Book.CourseProgramId);
            });
            ViewBag.Order = _context.Orders.Find(orderId);
            return View(applicationDbContext);
        }

        [Authorize(Roles = "Customer")]
        public IActionResult Create()
        {
            Models.Order order = JsonConvert.DeserializeObject<Models.Order>(HttpContext.Session.GetString("order"));
            List<Cart> cartList = JsonConvert.DeserializeObject<List<Cart>>(HttpContext.Session.GetString("cart"));
            cartList.ForEach(cart =>
            {
                _context.Add(new OrderDetail
                {
                    OrderId = order.OrderId,
                    BookId = cart.BookId
                });
                _context.SaveChanges();

            });
            return RedirectToAction("UpdateStock", "Books");
        }
        private bool OrderDetailExists(int id)
        {
            return _context.OrderDetails.Any(e => e.OrderDetailId == id);
        }
    }
}

Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GeorgianBudgetSaver.Data;
using GeorgianBudgetSaver.Models;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;

namespace GeorgianBudgetSaver.Controllers
{
    public class OrdersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OrdersController(ApplicationDbContext context)
        {
            _context = context;
        }
        [Authorize]
        // GET: Orders
        public async Task<IActionResult> Index()
        {
            if (User.IsInRole("Administrator"))
            {
                var allOrders = await _context.Orders.ToListAsync();
                return View(allOrders);
            }
            var orders = await _context.Orders.Where(order => order.CustomerId == User.Identity.Name).OrderBy(o => o.OrderDate).ToListAsync();
            return View(orders);
        }

        [Authorize(Roles = "Customer")]
        // GET: Orders/Create
        public IActionResult Create()
        {
            Models.Order order = JsonConvert.DeserializeObject<Models.Order>(HttpContext.Session.GetString("order"));
            _context.Add(order);
            _context.SaveChanges();
            string jsonString = System.Text.Json.JsonSerializer.Serialize(order);
            HttpContext.Session.SetString("order", jsonString);
            return RedirectToAction("Create", "OrderDetails");
        }

    }
}

Views/Orders/Create.cshtml
@model GeorgianBudgetSaver.Models.Order

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CustomerId" class="control-label"></label>
                <input asp-for="CustomerId" class="form-control" required />
                <span asp-validation-for="CustomerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" required />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" required />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Province" class="control-label"></label>
                <input asp-for="Province" class="form-control" required />
                <span asp-validation-for="Province" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostalCode" class="control-label"></label>
                <input asp-for="PostalCode" class="form-control" required />
                <span asp-validation-for="PostalCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" required />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Carts" asp-action="Index">Back To Cart</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Orders/Delete.cshtml
@model GeorgianBudgetSaver.Models.Order

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Order</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CustomerId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Province)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Province)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PostalCode)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PostalCode)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.OrderDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Total)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Total)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="OrderId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Orders/Details.cshtml
@model GeorgianBudgetSaver.Models.Order

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Order</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CustomerId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Province)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Province)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PostalCode)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PostalCode)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.OrderDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Total)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Total)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.OrderId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Orders/Edit.cshtml
@model GeorgianBudgetSaver.Models.Order

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="OrderId" />
            <div class="form-group">
                <label asp-for="CustomerId" class="control-label"></label>
                <input asp-for="CustomerId" class="form-control" />
                <span asp-validation-for="CustomerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Province" class="control-label"></label>
                <input asp-for="Province" class="form-control" />
                <span asp-validation-for="Province" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostalCode" class="control-label"></label>
                <input asp-for="PostalCode" class="form-control" />
                <span asp-validation-for="PostalCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderDate" class="control-label"></label>
                <input asp-for="OrderDate" class="form-control" />
                <span asp-validation-for="OrderDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Total" class="control-label"></label>
                <input asp-for="Total" class="form-control" />
                <span asp-validation-for="Total" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Orders/Index.cshtml
@model IEnumerable<GeorgianBudgetSaver.Models.Order>
@using System.Globalization
<div class="container" style="margin:6rem auto; width:60%;">
    @if (User.IsInRole("Administrator"))
    {
        <h1>All Order</h1>
    }
    else
    {
        <h1>My Order</h1>
    }
    <hr />
    @foreach (var item in Model)
    {
        <div class="card mb-2" style="background-color:#7180AC; padding-top:.2rem; border:none;">
            <div class="card-body list-group-item d-flex justify-content-between lh-condensed" style="background-color:white; border-radius:.2rem;">
                <div>
                    <h6 class="my-0">Order Number: #@item.OrderId</h6>
                    <small class="text-muted">Placed on: @String.Format("{0:d}", item.OrderDate)</small>
                </div>
                <form asp-controller="OrderDetails" asp-action="DetailsWithOrder" method="post" class="align-items-center">
                    <span class="align-middle">Total: @String.Format(new CultureInfo("en-US"),"{0:c}", item.Total)@("(CAD)")</span>
                    <input type="hidden" asp-for="@item.OrderId" name="orderId" />
                    <button type="submit" class="btn order-detail"><i class="bi bi-chevron-right"></i></button>
                </form>
            </div>
        </div>
    }

</div>